# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {

imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
boot.initrd.kernelModules = [ ];
boot.kernelModules = [ "kvm-intel" ];
boot.extraModulePackages = [ ];

fileSystems."/" = {
	device = "/dev/disk/by-uuid/b3f76bac-2f29-4a52-b45f-ed15336b57b7";
      	fsType = "ext4";
};

fileSystems."/boot" = {
	device = "/dev/disk/by-uuid/9BA6-149A";
      	fsType = "vfat";
      	options = [ "fmask=0077" "dmask=0077" ];
};

swapDevices = [ ];

environment.variables.NIXOS_OZONE_WL = "1";

nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
